name: PR Workflows

# Run action on pull request event
on: [pull_request]

jobs:
  # Build the site on every pull request.
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the commit from the pull request.
      - uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install node modules
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify
